getting and saving the train, valid and test data...
Traceback (most recent call last):
  File "./train.py", line 36, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./train.py", line 19, in main
    reader = Reader(config)
  File "/home/lafferty/abstracts_rnn/read_corpus.py", line 30, in __init__
    train_objs, valid_objs, test_objs = self._read_and_get_objdata(self.raw_data_root)
  File "/home/lafferty/abstracts_rnn/read_corpus.py", line 50, in _read_and_get_objdata
    obj = json.load(codecs.open(data_dir, "r", encoding="utf8"))
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'data/abstracts-small.json'
getting and saving the train, valid and test data...
creating the vocabulary...
('train length: ', 8502648)
('vocab tokens: ', [(u' ', 1238867), (u'e', 816168), (u't', 615228), (u'i', 540678), (u'a', 536183), (u'o', 500037), (u'n', 487713), (u's', 447862), (u'r', 430322), (u'l', 283206), (u'h', 257108), (u'c', 257001), (u'd', 225472), (u'm', 194584), (u'u', 178875), (u'p', 172991), (u'f', 157606), (u'g', 122461), (u'y', 96314), (u'b', 91769), (u'w', 76269), (u'v', 72337), (u'.', 59081), (u'$', 58476), (u',', 52781), (u'-', 40225), (u'\\', 39856), (u'{', 28689), (u'}', 28687), (u'x', 28648), (u'k', 23841), (u'T', 18830), (u'q', 16380), (u')', 15206), (u'(', 15040), (u'W', 14530), (u'1', 12971), (u'S', 12831), (u'0', 12575), (u'z', 11894), (u'I', 11071), (u'2', 10445), (u'A', 10328), (u'M', 10085), (u'C', 9994), (u'_', 9340), (u'H', 7374), (u'F', 7130), (u'L', 6995), (u'B', 6941), (u'P', 6750), (u'D', 6746), (u'^', 6626), (u'R', 6562), (u'G', 6547), (u'N', 5697), (u'3', 5579), (u'O', 5361), (u'E', 4954), (u'j', 4640), (u'5', 4468), (u"'", 4220), (u'4', 3853), (u'K', 3429), (u'V', 3013), (u'/', 2765), (u'=', 2608), (u'U', 2607), (u'6', 2456), (u':', 2443), (u'~', 2254), (u'7', 2202), (u'8', 2201), (u'9', 2187), (u'`', 1909), (u'X', 1898), (u'+', 1869), (u';', 1503), (u'J', 1438), (u'Q', 1415), (u'\xc3', 1377), (u'\xc2', 1225), (u'[', 1001), (u']', 999), (u'Z', 985), (u'Y', 743), (u'%', 712), (u'<', 699), (u'"', 686), (u'|', 598), (u'*', 552), (u'>', 530), (u'\x90', 416), (u'?', 243), (u'\x91', 196), (u'!', 157), (u'\xa2', 121)])
('vocab tokens length: ', 97)
('official vocab length: ', 100)
 [*] save ./data/abstracts-small/vocab.pkl
preparing final run data...
 [*] save ./data/abstracts-small/X_train.pkl
 [*] save ./data/abstracts-small/Y_train.pkl
 [*] save ./data/abstracts-small/X_valid.pkl
 [*] save ./data/abstracts-small/Y_valid.pkl
 [*] save ./data/abstracts-small/X_test.pkl
 [*] save ./data/abstracts-small/Y_test.pkl
vocabulary size: 100
number of training documents: 109072.0
number of validation documents: 11616.0
number of testing documents: 11616.0
2019-02-22 01:51:08.760343: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-02-22 01:51:09.839455: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2019-02-22 01:51:09.839586: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: abstract-rnn-gpu
2019-02-22 01:51:09.839596: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: abstract-rnn-gpu
2019-02-22 01:51:09.839668: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 410.72.0
2019-02-22 01:51:09.839734: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 410.72.0
2019-02-22 01:51:09.839785: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 410.72.0
WARNING:tensorflow:At least two cells provided to MultiRNNCell are the same object and will share weights.
 [*] Loading checkpoints...
checkpoints/abstracts-small/plainrnn/generator_embed_dim100__n_hidden500__n_layers2__init_lr0.001__decay_step20000__dropout0.5
 [!] Load failed...
generating eqs...
Traceback (most recent call last):
  File "./train.py", line 36, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./train.py", line 32, in main
    model.generate_eq(model.sess)
  File "/home/lafferty/abstracts_rnn/rnns.py", line 312, in generate_eq
    state = sess.run(self.final_state, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value generator/rnn/multi_rnn_cell/cell_0/lstm_cell/bias
	 [[node generator/rnn/multi_rnn_cell/cell_0/lstm_cell/bias/read (defined at /home/lafferty/abstracts_rnn/rnns.py:165)  = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](generator/rnn/multi_rnn_cell/cell_0/lstm_cell/bias)]]

Caused by op u'generator/rnn/multi_rnn_cell/cell_0/lstm_cell/bias/read', defined at:
  File "./train.py", line 36, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./train.py", line 22, in main
    model = RNNs(sess, config, reader)
  File "/home/lafferty/abstracts_rnn/rnns.py", line 58, in __init__
    self.build_model()
  File "/home/lafferty/abstracts_rnn/rnns.py", line 110, in build_model
    self.build_generator()
  File "/home/lafferty/abstracts_rnn/rnns.py", line 165, in build_generator
    dtype=tf.float32) # outputs: [batch_size, max_time, cell_state_size]  # state: LSTM tuple
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 664, in dynamic_rnn
    dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 872, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3260, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 838, in _time_step
    skip_conditionals=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 275, in _rnn_step
    new_output, new_state = call_cell()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 826, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 233, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1486, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1282, in __call__
    output, new_state = self._cell(inputs, state, scope=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 370, in __call__
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/utils/tf_utils.py", line 149, in wrapper
    output_shape = fn(instance, input_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 933, in build
    initializer=initializer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 495, in add_variable
    return self.add_weight(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 288, in add_weight
    getter=vs.get_variable)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 609, in add_weight
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/checkpointable/base.py", line 639, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 523, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 236, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 922, in _get_single_variable
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 183, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 146, in _variable_v1_call
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 125, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 2444, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 187, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 1329, in __init__
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 1488, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 81, in identity
    return gen_array_ops.identity(input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3454, in identity
    "Identity", input=input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value generator/rnn/multi_rnn_cell/cell_0/lstm_cell/bias
	 [[node generator/rnn/multi_rnn_cell/cell_0/lstm_cell/bias/read (defined at /home/lafferty/abstracts_rnn/rnns.py:165)  = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](generator/rnn/multi_rnn_cell/cell_0/lstm_cell/bias)]]

 [*] load ./data/abstracts-small/vocab.pkl
 [*] load ./data/abstracts-small/X_train.pkl
 [*] load ./data/abstracts-small/Y_train.pkl
 [*] load ./data/abstracts-small/X_valid.pkl
 [*] load ./data/abstracts-small/Y_valid.pkl
 [*] load ./data/abstracts-small/X_test.pkl
 [*] load ./data/abstracts-small/Y_test.pkl
vocabulary size: 100
number of training documents: 109072.0
number of validation documents: 11616.0
number of testing documents: 11616.0
2019-02-22 01:55:09.051564: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-02-22 01:55:10.858620: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2019-02-22 01:55:10.858702: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: abstract-rnn-gpu
2019-02-22 01:55:10.858713: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: abstract-rnn-gpu
2019-02-22 01:55:10.858791: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 410.72.0
2019-02-22 01:55:10.858842: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 410.72.0
2019-02-22 01:55:10.858857: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 410.72.0
WARNING:tensorflow:At least two cells provided to MultiRNNCell are the same object and will share weights.
 [*] Loading checkpoints...
checkpoints/abstracts-small/plainrnn/generator_embed_dim100__n_hidden500__n_layers2__init_lr0.001__decay_step20000__dropout0.5
 [!] Load failed...
generating eqs...
Traceback (most recent call last):
  File "./train.py", line 36, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./train.py", line 32, in main
    model.generate_eq(model.sess)
  File "/home/lafferty/abstracts_rnn/rnns.py", line 312, in generate_eq
    state = sess.run(self.final_state, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value generator/rnn/multi_rnn_cell/cell_0/lstm_cell/kernel
	 [[node generator/rnn/multi_rnn_cell/cell_0/lstm_cell/kernel/read (defined at /home/lafferty/abstracts_rnn/rnns.py:165)  = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](generator/rnn/multi_rnn_cell/cell_0/lstm_cell/kernel)]]

Caused by op u'generator/rnn/multi_rnn_cell/cell_0/lstm_cell/kernel/read', defined at:
  File "./train.py", line 36, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./train.py", line 22, in main
    model = RNNs(sess, config, reader)
  File "/home/lafferty/abstracts_rnn/rnns.py", line 58, in __init__
    self.build_model()
  File "/home/lafferty/abstracts_rnn/rnns.py", line 110, in build_model
    self.build_generator()
  File "/home/lafferty/abstracts_rnn/rnns.py", line 165, in build_generator
    dtype=tf.float32) # outputs: [batch_size, max_time, cell_state_size]  # state: LSTM tuple
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 664, in dynamic_rnn
    dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 872, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3260, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 838, in _time_step
    skip_conditionals=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 275, in _rnn_step
    new_output, new_state = call_cell()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 826, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 233, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1486, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1282, in __call__
    output, new_state = self._cell(inputs, state, scope=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 370, in __call__
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/utils/tf_utils.py", line 149, in wrapper
    output_shape = fn(instance, input_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 925, in build
    partitioner=maybe_partitioner)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 495, in add_variable
    return self.add_weight(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 288, in add_weight
    getter=vs.get_variable)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 609, in add_weight
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/checkpointable/base.py", line 639, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 523, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 236, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 922, in _get_single_variable
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 183, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 146, in _variable_v1_call
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 125, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 2444, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 187, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 1329, in __init__
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 1488, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 81, in identity
    return gen_array_ops.identity(input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3454, in identity
    "Identity", input=input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value generator/rnn/multi_rnn_cell/cell_0/lstm_cell/kernel
	 [[node generator/rnn/multi_rnn_cell/cell_0/lstm_cell/kernel/read (defined at /home/lafferty/abstracts_rnn/rnns.py:165)  = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](generator/rnn/multi_rnn_cell/cell_0/lstm_cell/kernel)]]

